### ISSUE TITLE
Does not work with SSR

### ISSUE THREAD

**Issue by mmarkelov** [VKCOM/icons#4]
```javascript
import React from 'react';
import Icon from '@vkontakte/icons/dist/36/like';
...
render() {
    ...
    <Icon />
    ...
}
```

will throw 
```
ReferenceError: document is not defined
    at BrowserSprite._autoConfigure (/Users/markel/Desktop/react-starter-kit/node_modules/svg-baker-runtime/browser-sprite.js:761:43)
    at new BrowserSprite (/Users/markel/Desktop/react-starter-kit/node_modules/svg-baker-runtime/browser-sprite.js:695:12)
....
```

I haven't got much experience **svg-baker-runtime**, but I suppose **'svg-baker-runtime/browser-sprite'** should be replaced.

For now I can use it like this:
```javascript
import React from 'react';
import Icon from '@vkontakte/icons/dist/36/like';
...
render() {
    ...
    {typeof window !== 'undefined' && <Icon />}
    ...
}
```

**Comment by ArthurStam** [comment]
Thanks for this issue. I should think.

**Comment by fedorov-xyz** [comment]
С версии 1.6.0 иконки умеют рендериться на сервере.
